### PR TITLE
Support /odm/etc/ & /my_product/etc/

### PR DESCRIPTION
**Pull request by reiryuki**
- Support /odm/etc/ & /my_product/etc/ audio files
- Support stage_policy.conf
- Remove duplicate
- Fix context

### CODE REVIEW

**Comment by Zackptg5** [comment]
I'll need to do some more digging on this but I'll definitely work on adding them in. Did oneplus really make up a new partition name "my_product"? I can't stand them anymore.

**Comment by reiryuki** [comment]
Actually yes

**Comment by Zackptg5** [comment]
There is a problem with this: AML is designed to use existing magisk mount files. odm and my_product are not directories magisk would mount. Each audio module that would target these directories would have to mount them manually. The problem is that since it'd be outside of magisk mount, there's no way to no exactly when each module would do this and so aml couldn't reliably unmount and use it's own. 
Long and short of it, there's no good way to incorporate this into aml yet until magisk supports mounting them like with product, system, vendor, etc.

Here's the issue for it: https://github.com/topjohnwu/Magisk/issues/3338
Here's where you can see currently supported partitions: https://github.com/topjohnwu/Magisk/blob/master/native/src/core/bootstages.cpp#L77

**Comment by reiryuki** [comment]
ok then 👌

**Comment by HuskyDG** [comment]
https://github.com/HuskyDG/Magisk/commit/337626c0bc354ee33611f75647a438e887c9c2f2

**Comment by reiryuki** [comment]
@Zackptg5 Hi, Magisk Delta Canary now supports $MAGISKTMP/.magisk/mirror/odm & $MAGISKTMP/.magisk/mirror/my_product. Please check my latest pull request changes 🙏🙏🙏. Previous force mount bind is removed. Since there is no actual /system/odm & /system/my_product but only /odm & /my_product, so I have to fix umount & mount in service.sh, otherwise it cannot be mounted correctly. Also every ROM has /etc & /vendor/etc dir even it's only a symlink, so it's not a problem if I redirect umount & mount files from /system/etc/ to /etc/ instead and /system/vendor/ to /vendor/ instead.

Misc changes:
- "lists=" fixes audio_device.xml duplicated comments & supports stage_policy.conf Samsung file.
- Vendor contexts are only required for SDK 26 and bellow, otherwise not.

**Comment by Zackptg5** [comment]
> @Zackptg5 Hi, Magisk Delta Canary now supports $MAGISKTMP/.magisk/mirror/odm & $MAGISKTMP/.magisk/mirror/my_product. Please check my latest pull request changes 🙏🙏🙏. Previous force mount bind is removed. Since there is no actual /system/odm & /system/my_product but only /odm & /my_product, so I have to fix umount & mount in service.sh, otherwise it cannot be mounted correctly. Also every ROM has /etc & /vendor/etc dir even it's only a symlink, so it's not a problem if I redirect umount & mount files from /system/etc/ to /etc/ instead and /system/vendor/ to /vendor/ instead.
> 
> Misc changes:
> 
>     * "lists=" fixes audio_device.xml duplicated comments & supports stage_policy.conf Samsung file.
> 
>     * Vendor contexts are only required for SDK 26 and bellow, otherwise not.

Delta canary is an unofficial fork, official magisk canary doesn't have this integrated yet, no pull request is present on the official repo either. I only support official magisk releases

**Comment by reiryuki** [comment]
alright

**Comment by Zackptg5** [comment]
Gonna reopen this in the event official magisk finally supports some of these parititions

**Comment by reiryuki** [comment]
sounds good 👌👍

**Comment by Zackptg5** [comment]
Looks like progress is finally being made on this: https://github.com/topjohnwu/Magisk/issues/2359#event-8608806039, https://github.com/topjohnwu/Magisk/issues/3338

Once they get it finalized, I'll post a test build

**Comment by Zackptg5** [comment]
Update on this. Since it appears that no progress will be made on this for a while (if ever), I'm going to add support for magisk delta. I'll also be adding support for KSU. No timeline on this yet but I am working on it as able

**Comment by Zackptg5** [comment]
@reiryuki which kinds of audio files are in odm and my_product for you?

**Comment by reiryuki** [comment]
@Zackptg5 /odm/etc/ is audio effects xml and /my_product/etc/ is usually audio policy configurations xml

btw I have already made AML with new Magisk v26+, Magisk Delta, and also KSU support here: https://github.com/reiryuki/Audio-Modification-Library-Ryuki-Mod-Magisk-Module

Do you want I merge it here?

**Comment by Zackptg5** [comment]
I'm going to merge it to test branch and then make some other changes. Testing for KSU is challenging for me cause I only have WSA to work with atm.
Still have some outstanding behavioral changes in KSU I'm waiting on to see if they'll be addressed or not as I may need to tweak some things: https://github.com/tiann/KernelSU/issues/726

**Comment by reiryuki** [comment]
@Zackptg5 btw new official magisk no longer using /dev/ as mirror and you don't need mirror at post-fs-data because files are not changed yet

**Comment by Zackptg5** [comment]
> @Zackptg5 btw new official magisk no longer using /dev/ as mirror and you don't need mirror at post-fs-data because files are not changed yet

Interesting, looks like /dev mirror is still present for now but you're right in that it's not needed anymore. KernelSU is the same with post-fs-data before mounting. I'm pretty sure some mounting used to happen before or around the same time back in the day, looks like it was before v20.4 though which is min supported magisk currently. Removing the whole mirror thing makes this much easier
The interesting thing is, `magisk --path` wasn't available for use during part of the post-fs-data part of the boot process originally in some testing scenarios which is why I haven't used it but appears that's been fixed too.
Looks like I got more updating to do :)
Thanks!

**Comment by Zackptg5** [comment]
@HuskyDG Can you add a page to your github.io page with current supported partitions in magisk delta? I'm planning on adding on adding support for them to my MMTEX template (for mods like jdsp) and was going to link to it in my wiki

**Comment by Zackptg5** [comment]
@reiryuki Quick update, got the gist of it worked out (I think). The vendor mounting is janky but works. Uninstall is broken, kernelsu runs uninstall immediately rather than at next boot so I changed the uninstall script to a post-fs-data one for ksu installs. Thoughts?

**Comment by reiryuki** [comment]
@Zackptg5  you also need to prepare vendor folder at installation, because ksu is using $MODPATH/vendor instead of $MODPATH/system/vendor

**Comment by reiryuki** [comment]
@Zackptg5 there is a problem with official aml if an audio mod module is copying audio files while post-fs-data instead of while installation, so, I delete some functions that "removing files"

**Comment by reiryuki** [comment]
@HuskyDG no if $MODPATH/system/vendor is not prepared while installation

**Comment by reiryuki** [comment]
@HuskyDG $MODPATH/system/vendor must be prepared while installation, otherwise it can't be handled with ksu

**Comment by reiryuki** [comment]
@HuskyDG oh so, that's a new commit
I see

**Comment by Zackptg5** [comment]
@reiryuki you can move everything to $MODPATH/vendor and create a symlink from /vendor to $MODPATH/system/vendor in post-fs-data and it's effectively the same as what ksu does on it's own during normal install

**Comment by Zackptg5** [comment]
> @Zackptg5 there is a problem with official aml if an audio mod module is copying audio files while post-fs-data instead of while installation, so, I delete some functions that "removing files"

I got that one figured out. Some changes in paths and stuff with the changes in mounting behavior and with magisk I needed to re-bind mount while with ksu I just have to remount the overlays

**Comment by reiryuki** [comment]
@Zackptg5 at aml ryuki mod it's already confugured correctly

**Comment by Zackptg5** [comment]
> @Zackptg5 at aml ryuki mod it's already confugured correctly
I did some similar stuff to your branch, think it's good to go if you want to check out the testing branch. I'm going to wait for next ksu update first though since there was the symlink fix

**Comment by Zackptg5** [comment]
> @Zackptg5 at aml ryuki mod it's already confugured correctly

I did some similar stuff to your branch, think it's good to go if you want to check out the testing branch. I'm going to wait for next ksu update first though since there was the symlink fix

**Comment by reiryuki** [comment]
@Zackptg5 I don't think $KSU & $MAGISK_VER variable is available in service.sh and post-fs-data.sh. As far as I know, $KSU & $MAGISK_VER variable is only available in customize.sh while installation. Your $KSU & $MAGISK_VER variable in post-fs-data.sh and service.sh will always be empty even in KernelSU or Magisk Delta. There is no even built-in variable in post-fs-data.sh and service.sh. CMIIW.

**Comment by Zackptg5** [comment]
KSU actually was accessible for me in the boot scripts. I forgot about MAGISK_VER so I'm going to need to change that

**Comment by Zackptg5** [comment]
> You can hardcode KSU=true/false into your boot script while installation.
> You don't have to decide whenever boot script is executed under magisk or ksud. Why?
>  `/data/adb/modules` is treated different between Magisk and ksud.
> - When Magisk is not installed, ksud will mount `/data/adb/ksu/modules.img` to `/data/adb/modules` and the original content of Magisk's `/data/adb/modules` is now replaced by KernelSU's one
> - When Magisk is installed, ksud will skipped
> 
> That means your modules will be installed into `/data/adb/ksu/modules.img` if it is flashed from KernelSU and it is safely to hardcode your boot script as KernelSU-only, so in `customize.sh`, I can write like this:
> ```bash
> if [ "$KSU" == true ]; then
>     sed -i "s/^KERNELSU=false/KERNELSU=true/g" post-fs-data.sh
> fi
> ```

I may hard code it but I do need to know if it's ksu or delta so I know which partitions are supported and where to place files since symlinks are different between ksu and magisk.

Edit: Pushed fix to testing branch: 332254eb810440308ecaf785a0768d3b8f36cb42
Might wait for next kernelsu release though cause it'll change some of the scripting logic (can get rid of some workarounds)

**Pull request merged**
