### PR TITLE
Audio Modifikacion 

### PR DESCRIPTION
**Pull request by ghost**
Pls upgrade

### CODE REVIEW

**Comment by ghost** [comment]
Nádherné

**Review by ghost — COMMENTED** [review]
Thanks

**Comment by Zackptg5** [comment]
diff3 branch is dead. It was an idea I had that didn't pan out. Master is the up to date one and only relevant one. I just keep the diff3 one in case I want to look back at it in the future for something else

**Comment by ghost** [comment]
Open pls

**Pull request closed without merging**
